### ISSUE TITLE
Failed to load the tree-view-git-branch-fix package

### ISSUE THREAD

**Issue by camlafit** [yubaoquan/tree-view-git-branch-fix#2]
Follows #1 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [tree-view-git-branch-fix](https://github.com/yubaoquan/tree-view-git-branch-fix) package 0.3.4

### Stack Trace

Failed to load the tree-view-git-branch-fix package

```
At Cannot find module 'clipboardy'

Error: Cannot find module 'clipboardy'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/tree-view-git-branch-fix/lib/repository.js:9:20)
    at /packages/tree-view-git-branch-fix/lib/repository.js:211:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/tree-view-git-branch-fix/lib/main.js:3:43)
    at /packages/tree-view-git-branch-fix/lib/main.js:185:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:903:35)
    at /usr/share/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:617:16)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:550:25)
    at PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:243:29)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
```

### Non-Core Packages

```
adwaita-pro-ui 2.1.5 
atom-beautify 0.30.9 
atom-ide-ui 0.6.0 
docblockr 0.13.3 
ide-php 0.7.3 
project-viewer 1.2.5 
tree-view-git-branch-fix 0.3.4 
```

**Comment by yubaoquan** [comment]
update to 0.3.5

**Comment by camlafit** [comment]
great :)
